config/routes.rb
Rails.application.routes.draw do
  get 'animals/rats', to: "animals#rats", as: "rats"
  get 'animals/roaches', to: "animals#roaches", as: "roaches"
  get 'animals/flys', to: "animals#flys", as: "flys"
  # get 'boroughs/manhatten' to 'manhatten' 
  get 'boroughs/manhatten', to: "boroughs#manhatten", as: "manhatten"
  get 'boroughs/queens', to: "boroughs#queens", as: "queens"
  get 'boroughs/bronx', to: "boroughs#bronx", as: "bronx"
  get 'boroughs/brooklyn', to: "boroughs#brooklyn", as: "brooklyn"
  get 'boroughs/statenisland', to: "boroughs#statenisland", as: "statenisland"
  get 'rating/index'
  get 'main_page/index'
  get 'bronx/index'
  get 'search/index', to: "search#index", as: "search"

  root 'home#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def rats
  end

  def roaches
  end

  def flys
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/boroughs_controller.rb
class BoroughsController < ApplicationController
  def manhatten
  end

  def queens
  end

  def bronx
  end

  def brooklyn
  end

  def statenisland
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
    def index 
    end
end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boroughs_helper.rb
module BoroughsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/animals/flys.html.erb
<div class = "container">
<div id = "flys">
  <%# all flys api information dispalyed here %>
</div>
</div>

app/views/animals/rats.html.erb
<div class = "container">
<div id = "rats">
  <%# all rats api information dispalyed here %>
</div>
</div>

app/views/animals/roaches.html.erb
<div class = "container">
<div id = "roaches">
  <%# all roaches api information dispalyed here %>
</div>
</div>

app/views/boroughs/bronx.html.erb
  



<h1 class = "boro-header"></h1>

<div class = "container">
<div id = "bronx">
  <%# all bronx api information dispalyed here %>
</div>
</div>

app/views/boroughs/brooklyn.html.erb
  


<h1 class = "boro-header"></h1>

<div class = "container">
<div id = "brooklyn">
  <%# all brooklyn api information dispalyed here %>
</div>
</div>

app/views/boroughs/manhatten.html.erb
  

<h1 class = "boro-header"></h1>

<div class = "container">
<div id = "manhatten">
  <%# all manhatten api information dispalyed here %>
</div>
</div>

app/views/boroughs/queens.html.erb
<h1 class = "boro-header"></h1>

<div class = "extra-space container">
<div id = "queens">
  <%# all queens api information dispalyed here %>
</div>
</div>

app/views/boroughs/statenisland.html.erb
  


<h1 class = "boro-header"></h1>

<div class = "container">
<div id = "statenisland">
  <%# all statenisland api information dispalyed here %>
</div>
</div>

app/views/home/index.html.erb
<br>
<div class = "row justify-content-center">

<%=link_to roaches_path, class: "nav-item nav-link" do %>
  <%= image_tag("cockroach-silhouette.svg", class: "img-thumbnail bg-light", id: "roach") %>
  <%end%>

<%=link_to rats_path, class: "nav-item nav-link" do %>
  <%= image_tag("rat-looking-right.svg", class: "img-thumbnail bg-light ", id: "rat") %>
  <%end%>

<%=link_to flys_path, class: "nav-item nav-link" do %>
  <%= image_tag("fly-shape.svg", class: "img-thumbnail bg-light", id: "fly") %>
   <%end%>

</div>
<br>
<p class = "center">
  Updated Daily, search by zip below or view a list above
</p>

</div>

<div ="top">

</div>
<div class = "d-flex justify-content-center">
<form action="/search/index">
  Zip Code: 
  <input type="text" name="search" value="">
  
  <input type="submit" value="Submit">
</form>
</div>

<div class = "d-flex justify-content-center">
<br>
  <%# <p>Worst Inspection Rating In NYC:</p> %>
</div>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>FoodGrade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# google font links below %>
    <%# bootstrap link below %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :javascript_includes %>
    <link href="//fonts.googleapis.com/css?family=Black+Ops+One|Bowlby+One+SC|Ceviche+One|Creepster|Faster+One|Frijole|Londrina+Outline|Montserrat+Subrayada|Ruslan+Display|Shojumaru|Zilla+Slab+Highlight|" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <%# favicon %>
    <%= favicon_link_tag 'cockroach-silhouette.svg' %>
  </head>

  <body>

<%# navbar %>
<nav class="navbar navbar-dark bg-dark justify-content-center">
  <a class="text-center navbar-brand" href="/">NYC FOOD SAFETY RATINGS</a>
</nav>
<%# secondary navbar %>
<nav class="nav nav-pills nav-fill nav-light bg-light">
  <%=link_to manhatten_path, class: "nav-item nav-link" do %>Manhattan<%end%>
  <%=link_to brooklyn_path, class: "nav-item nav-link" do %>Brooklyn<%end%>
  <%=link_to queens_path, class: "nav-item nav-link" do %>Queens<%end%>
  <%=link_to bronx_path, class: "nav-item nav-link" do %>Bronx<%end%>
  <%=link_to statenisland_path, class: "nav-item nav-link" do %>Staten Island<%end%>
</nav>


    <%= yield %>


<%# axios link below %>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<%# bootstrap links below %>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>





</body>
<footer> </footer>

</html>

app/views/main_page/index.html.erb
<p>this is the main page</p>

app/views/rating/index.html.erb
<h1>Rating#index</h1>
<p>Find me in app/views/rating/index.html.erb</p>

app/views/search/index.html.erb
<div class = "container">
<div id = "search">


  <%# all manhattan api information dispalyed here %>
<script>
  
document.addEventListener('DOMContentLoaded', domContentLoadedEvent => {

    class Resturant {
        constructor(name, boro, critical, score, street, violation, zipcode,grade) {
            this.name = name
            this.boro = boro
            this.critical = critical
            this.score = score
            this.street = street
            this.violation = violation
            this.zipcode = zipcode
            this.grade = grade
        }
    }
  
    let ul = document.createElement("ul")
    let divQueens = document.getElementById("search")
    if (divQueens != null) {
    
    axios.get('https://data.cityofnewyork.us/resource/9w7m-hzhe.json')
    .then((response) => {
  
            let data = response.data
            let allData = []
  
  
            
  
            for (let x = 0; x < data.length; x++) {
                let body = document.querySelector("body")
                let ul = document.createElement("ul")
                let name = document.createElement("li")
                let boro = document.createElement("li")
                let critical = document.createElement("li")
                let score = document.createElement("li")
                let street = document.createElement("li")
                let violation = document.createElement("li")
                let zipcode = document.createElement("li")
                let grade = document.createElement("li")
  
                let resturant = new Resturant(
                    data[x].dba,
                    data[x].boro,
                    data[x].critical_flag,
                    data[x].score,
                    data[x].street,
                    data[x].violation_description,
                    data[x].zipcode,
                    data[x].grade
                )
  
                name.innerHTML = "<strong> <br>" + resturant.name + "</strong>"
                street.innerHTML = "<strong>" + resturant.street + " " + resturant.boro + " " + resturant.zipcode + "</strong> <br> <br>"
                critical.innerHTML = "Status: " + resturant.critical
                score.innerHTML = "Score: " + resturant.score + "<br> <br>"
                violation.innerHTML = "Violation: " + resturant.violation + "<br> <br>"
                grade.innerHTML = "grade: " + "<strong>" + resturant.grade + "</strong>"

                
                // enter search params
                if (data[x].zipcode == <%= params[:search] %>) { 
                
                ul.appendChild(grade)
                ul.appendChild(name)
                ul.appendChild(street)
                ul.appendChild(critical)
                ul.appendChild(score)
                ul.appendChild(violation)
            
                body.appendChild(divQueens)
                divQueens.appendChild(ul)
  
  
                
                }
  
            }
        })
        
    }
})

</script>

</div>
</div>